const INIT_MAZE = 'INIT_MAZE';
const MOVE_TRACTORS = 'MOVE_TRACTORS';
const STATUS_GENERATING_MAZE = 'Генерация';
const STATUS_GENERATED = 'Завершено';
const INIT_PLAYERS = 'INIT_PLAYERS';
const MOVE_PLAYERS = 'MOVE_PLAYERS';
const STATUS_GAMING = 'Игра';
const STATUS_GAMEOVER = 'Конец'
const STATUS_READY_GENERATING_MAZE = 'Настроено';
const STATUS_INSTALL_SETTINGS = 'STATUS_INSTALL_SETTINGS';

export {INIT_MAZE,
        MOVE_TRACTORS,
        STATUS_GENERATING_MAZE,
        STATUS_GENERATED,
        STATUS_GAMING,
        INIT_PLAYERS,
        MOVE_PLAYERS,
        STATUS_READY_GENERATING_MAZE,
        STATUS_GAMEOVER,
        STATUS_INSTALL_SETTINGS};